name: "CLA Assistant"
on:
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened,closed,synchronize ]

jobs:
  CLAssistant:
    runs-on: ubuntu-20.04
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the DCO Document and I hereby sign the DCO') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/dco.json'
          path-to-document: 'https://github.com/props-sh/dco/blob/main/DCO'
          # branch should not be protected
          branch: 'main'
          allowlist: bot*
          remote-organization-name: 'props-sh'
          remote-repository-name: 'dco'
          signed-commit-message: '$contributorName has signed the CLA in #$pullRequestNo'
          custom-allsigned-prcomment: '**CLA Assistant bot** All Contributors have signed the DCO.'
          use-dco-flag: true